### ISSUE TITLE
Could not build with the acrgo build-bpf (sub command not found)

### ISSUE THREAD

**Issue by sudophils** [SushantChandla/solana-crowd-funding#1]
![Screen Shot 2022-02-11 at 2 44 19 PM](https://user-images.githubusercontent.com/5889921/153602172-06d3b124-0c3d-430e-ab44-b677d1925e0b.png)
Kindly assist if; am stuck with going further

**Comment by SushantChandla** [comment]
https://stackoverflow.com/a/68645098/14462912 :)

**Comment by sudo-champ** [comment]
Thanks i sorted the above after adding writing the UI code, i seems to not getting the style. also this error when i click in the butto
![Screen Shot 2022-02-15 at 4 34 52 PM](https://user-images.githubusercontent.com/82091832/154095325-0a6cd548-cfca-4217-a8f0-32a40fba5e69.png)
n

**Comment by fleecyeth** [comment]
> Thanks i sorted the above after adding writing the UI code, i seems to not getting the style. also this error when i click in the butto ![Screen Shot 2022-02-15 at 4 34 52 PM](https://user-images.githubusercontent.com/82091832/154095325-0a6cd548-cfca-4217-a8f0-32a40fba5e69.png) n



> 

U have to add this in ur index.html

link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
    integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" /
    in the head tag
