### ISSUE TITLE
Program Questions

### ISSUE THREAD

**Issue by MarioProjects** [SushantChandla/solana-crowd-funding#3]
Hey Sushant thanks for your amazing work!

I have a question regarding the withdraw and donate functions. You are sending a pubkey as `writing_account` at the frontend, for example, 'asdku891123hj9f12jiopjiopaskl', to say something, but at the code, you retrieve the Campaign details by using `CampaignDetails::try_from_slice(*writing_account.data.borrow())`

Does Rust/Borsh all the work to fetch the account details with `try_from_slice` calling the blockchain to retrieve the pubkey info and then formating it with CampaignDetails struct on the back? Or maybe I misunderstood something.

Thanks again!

**Comment by SushantChandla** [comment]
No, we are not retrieve data from blockchain with try_from_slice.
We already have the data, store in the account. But the data is store in a buffer of 0's and 1's. 
Borsh stands for Binary Object Representation Serializer for Hashing. It is a sort of a standard used to serialize data to buffer of 0's and 1's  and deserialize back to Rust data type. `try_from_slice` will deseralize data.

https://gist.github.com/SushantChandla/45b791239a4cd9d9aea1db2107a58cda

In other project you will mostly see `try_from_slice_unchecked` used it basically ignores some buffer length constraint while deserializing.
