### ISSUE TITLE
Error when i click in the button for "Create Campaign"

### ISSUE THREAD

**Issue by fpreactrn** [SushantChandla/solana-crowd-funding#5]
Hi Sushant,  

Thanks you so much for your great tutorial "Build a Crowdfunding platform on Solana" on Figment Learn, and the code example! As a beginner, I have been really enjoying learning Solana by following your example. It is challenging but I am able to figure out most of the challenges, except this error when I clicked the "CreateCampaign" button:
![Screen Shot 2022-04-07 at 11 48 41 PM](https://user-images.githubusercontent.com/74478719/162359920-2e3f0776-0596-45c4-bfa7-dabfa698dbcb.png)

Can you please kindly help me figure out what went wrong. Thanks again!

Best regards,

Forrest

**Comment by SushantChandla** [comment]
Try googling the error to find a fix. Code work on my end so can't help much.

https://stackoverflow.com/questions/67804053/uncaught-referenceerror-buffer-is-not-defined-in-react

**Comment by fpreactrn** [comment]
Hi Sushant, 

Thanks for your response. So following your suggestions, I did my research, and I sorted out, this issue is caused by the version of React. The solution is: 1 deleted "node_modules" 2. copy the dependencies version from your package.json file, 3. npm install, and it works
